//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRS.DAL.EntityFramework
{
    using SGRS.Entity.BaseEF;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGRS_Conexion : DbContext
    {
        public SGRS_Conexion()
            : base("name=SGRS_Conexion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PARAMETRO> PARAMETRO { get; set; }
        public virtual DbSet<UBIGEO> UBIGEO { get; set; }
        public virtual DbSet<ACCION> ACCION { get; set; }
        public virtual DbSet<ASIGNACION> ASIGNACION { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
        public virtual DbSet<MODULO> MODULO { get; set; }
        public virtual DbSet<OPCION> OPCION { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PERMISOS> PERMISOS { get; set; }
        public virtual DbSet<SISTEMA> SISTEMA { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
