//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRS.Entity.BaseEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIGNACION
    {
        public int CODIGO_ASIGNACION { get; set; }
        public int CODIGO_SISTEMA { get; set; }
        public int CODIGO_USUARIO { get; set; }
        public int CODIGO_PERFIL { get; set; }
        public bool ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string TERMINAL_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string TERMINAL_MODIFICACION { get; set; }
    
        public virtual SISTEMA SISTEMA { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual PERFIL PERFIL { get; set; }
    }
}
