//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRS.Entity.BaseEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODULO()
        {
            this.OPCION = new HashSet<OPCION>();
        }
    
        public int CODIGO_MODULO { get; set; }
        public int CODIGO_SISTEMA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> MODULO_PADRE { get; set; }
        public string GLYPHICON { get; set; }
        public string RUTA_IMAGEN { get; set; }
        public string CONTROLADOR { get; set; }
        public string METODO { get; set; }
        public string AREA { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string TERMINAL_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string TERMINAL_MODIFICACION { get; set; }
    
        public virtual SISTEMA SISTEMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPCION> OPCION { get; set; }
    }
}
