//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRS.Entity.BaseEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISOS
    {
        public int CODIGO_PERMISOS { get; set; }
        public int CODIGO_PERFIL { get; set; }
        public int CODIGO_ACCION { get; set; }
        public int CODIGO_OPCION { get; set; }
        public bool ESTADO_PERMISO { get; set; }
        public bool ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string TERMINAL_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string TERMINAL_MODIFICACION { get; set; }
    
        public virtual ACCION ACCION { get; set; }
        public virtual OPCION OPCION { get; set; }
        public virtual PERFIL PERFIL { get; set; }
    }
}
